package com.heronix.model.domain;

import com.heronix.model.enums.EnrollmentRequestStatus;
import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.ToString;

import java.time.LocalDateTime;

/**
 * Course Enrollment Request Entity
 * Tracks student requests to enroll in courses with priority scoring
 *
 * This entity is central to the AI-powered course assignment system.
 * It stores each student's course preferences along with their calculated
 * priority scores for fair, transparent course assignment.
 *
 * @author Heronix Scheduling System Team
 * @version 1.0.0
 * @since Phase 3 - November 20, 2025
 */
@Entity
@Table(name = "course_enrollment_requests",
       uniqueConstraints = @UniqueConstraint(columnNames = {"student_id", "course_id"}))
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CourseEnrollmentRequest {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Student making the enrollment request
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id", nullable = false)
    @ToString.Exclude
    private Student student;

    /**
     * Course being requested
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_id", nullable = false)
    @ToString.Exclude
    private Course course;

    /**
     * Request priority (1 = first choice, 2 = second choice, etc.)
     * 1 = Highest priority (student's top choice)
     * 4 = Alternate choice
     */
    @Column(name = "preference_rank")
    private Integer preferenceRank;

    /**
     * Calculated priority score (higher = more priority)
     * Based on GPA, behavior, seniority, special needs, etc.
     * Typical range: 200-900 points
     */
    @Column(name = "priority_score")
    private Integer priorityScore;

    /**
     * Request status
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "request_status", nullable = false)
    private EnrollmentRequestStatus requestStatus = EnrollmentRequestStatus.PENDING;

    /**
     * When request was created (timestamp)
     */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /**
     * When request was processed (approved/denied)
     */
    @Column(name = "processed_at")
    private LocalDateTime processedAt;

    /**
     * Reason for approval/denial/status change
     * Examples: "Approved via AI assignment", "Denied - course full",
     *           "Waitlisted - 30/30 enrolled", "Denied - GPA below 3.0 requirement"
     */
    @Column(name = "status_reason", columnDefinition = "TEXT")
    private String statusReason;

    /**
     * Is this a waitlist request?
     */
    @Column(name = "is_waitlist")
    private Boolean isWaitlist = false;

    /**
     * Waitlist position (if waitlisted)
     * Position 1 = first in line for open seat
     */
    @Column(name = "waitlist_position")
    private Integer waitlistPosition;

    /**
     * Manually assigned by administrator (bypasses auto-assignment)
     * true = admin manually enrolled student
     * false = AI algorithm assigned
     */
    @Column(name = "manually_assigned")
    private Boolean manuallyAssigned = false;

    /**
     * Administrator who manually assigned (if applicable)
     * Username or ID of admin
     */
    @Column(name = "assigned_by")
    private String assignedBy;

    /**
     * Additional notes about this enrollment request
     */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /**
     * Academic year/term for this request
     */
    @Column(name = "academic_year_id")
    private Long academicYearId;

    /**
     * Whether this request was auto-generated by the system
     * (vs manually submitted by student)
     */
    @Column(name = "auto_generated")
    private Boolean autoGenerated = false;

    // ========================================================================
    // LIFECYCLE CALLBACKS
    // ========================================================================

    /**
     * Set creation timestamp before persisting
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();

        // Auto-calculate priority score if not set and student is available
        if (priorityScore == null && student != null) {
            priorityScore = student.calculatePriorityScore();
        }

        // Default status to PENDING if not set
        if (requestStatus == null) {
            requestStatus = EnrollmentRequestStatus.PENDING;
        }
    }

    /**
     * Update processed timestamp when status changes to final state
     */
    @PreUpdate
    protected void onUpdate() {
        // Set processed timestamp when moving to final status
        if (processedAt == null && requestStatus != null && requestStatus.isFinalStatus()) {
            processedAt = LocalDateTime.now();
        }
    }

    // ========================================================================
    // UTILITY METHODS
    // ========================================================================

    /**
     * Get human-readable description of this request
     */
    public String getRequestDescription() {
        if (student == null || course == null) {
            return "Invalid request (missing student or course)";
        }

        String preferenceText = switch (preferenceRank != null ? preferenceRank : 0) {
            case 1 -> "1st choice";
            case 2 -> "2nd choice";
            case 3 -> "3rd choice";
            case 4 -> "Alternate";
            default -> "Unknown preference";
        };

        return String.format("%s - %s (%s, Priority: %d)",
            student.getFullName(),
            course.getCourseName(),
            preferenceText,
            priorityScore != null ? priorityScore : 0);
    }

    /**
     * Check if this request is still pending (can be processed)
     */
    public boolean isPending() {
        return requestStatus == EnrollmentRequestStatus.PENDING;
    }

    /**
     * Check if this request was approved (student enrolled)
     */
    public boolean isApproved() {
        return requestStatus == EnrollmentRequestStatus.APPROVED ||
               requestStatus == EnrollmentRequestStatus.ALTERNATE_ASSIGNED;
    }

    /**
     * Check if this request was denied
     */
    public boolean isDenied() {
        return requestStatus == EnrollmentRequestStatus.DENIED;
    }

    /**
     * Check if student is on waitlist
     */
    public boolean isOnWaitlist() {
        return requestStatus == EnrollmentRequestStatus.WAITLISTED ||
               Boolean.TRUE.equals(isWaitlist);
    }

    /**
     * Approve this request and enroll student
     */
    public void approve(String reason, String assignedByUser) {
        this.requestStatus = EnrollmentRequestStatus.APPROVED;
        this.statusReason = reason;
        this.assignedBy = assignedByUser;
        this.processedAt = LocalDateTime.now();
        this.isWaitlist = false;
        this.waitlistPosition = null;
    }

    /**
     * Deny this request
     */
    public void deny(String reason) {
        this.requestStatus = EnrollmentRequestStatus.DENIED;
        this.statusReason = reason;
        this.processedAt = LocalDateTime.now();
        this.isWaitlist = false;
        this.waitlistPosition = null;
    }

    /**
     * Add to waitlist
     */
    public void addToWaitlist(int position, String reason) {
        this.requestStatus = EnrollmentRequestStatus.WAITLISTED;
        this.isWaitlist = true;
        this.waitlistPosition = position;
        this.statusReason = reason;
    }

    /**
     * Promote from waitlist to enrolled
     */
    public void promoteFromWaitlist(String reason, String assignedByUser) {
        this.requestStatus = EnrollmentRequestStatus.APPROVED;
        this.statusReason = reason;
        this.assignedBy = assignedByUser;
        this.processedAt = LocalDateTime.now();
        this.isWaitlist = false;
        this.waitlistPosition = null;
    }

    /**
     * Assign to alternate course
     */
    public void assignAlternate(String reason) {
        this.requestStatus = EnrollmentRequestStatus.ALTERNATE_ASSIGNED;
        this.statusReason = reason;
        this.processedAt = LocalDateTime.now();
    }

    /**
     * Get priority bonus based on preference rank
     * 1st choice gets highest bonus
     */
    public int getPreferenceBonus() {
        if (preferenceRank == null) return 0;

        return switch (preferenceRank) {
            case 1 -> 100;  // 1st choice
            case 2 -> 75;   // 2nd choice
            case 3 -> 50;   // 3rd choice
            case 4 -> 25;   // Alternate
            default -> 0;
        };
    }

    /**
     * Get total priority score including preference bonus
     */
    public int getTotalPriorityScore() {
        int base = priorityScore != null ? priorityScore : 0;
        return base + getPreferenceBonus();
    }

    /**
     * Get days waiting (for waitlist priority)
     */
    public long getDaysWaiting() {
        if (createdAt == null) return 0;
        return java.time.Duration.between(createdAt, LocalDateTime.now()).toDays();
    }

    /**
     * Get human-readable status display
     */
    public String getStatusDisplay() {
        if (requestStatus == null) return "Unknown";

        String status = requestStatus.getDisplayName();

        if (isWaitlist && waitlistPosition != null) {
            status += " (#" + waitlistPosition + ")";
        }

        return status;
    }

    /**
     * Get formatted preference rank label
     */
    public String getPreferenceRankLabel() {
        if (preferenceRank == null) return "Unknown";

        return switch (preferenceRank) {
            case 1 -> "1st Choice";
            case 2 -> "2nd Choice";
            case 3 -> "3rd Choice";
            case 4 -> "Alternate";
            default -> String.valueOf(preferenceRank);
        };
    }
}
